services:
  offer-db:
    image: postgres:16.3-alpine
    expose:
      - 5460
    ports:
      - "5460:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123offer
      - POSTGRES_DB=offer_db