"""second migration

Revision ID: 8e94c16b6a7e
Revises: 350e789f4b5e
Create Date: 2024-12-27 22:01:11.682181

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e94c16b6a7e"
down_revision: Union[str, None] = "350e789f4b5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offer_price_detailss",
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("caption", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["offer_id"], ["offers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "offer_types", sa.Column("offer_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        None, "offer_types", "offers", ["offer_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("offers", sa.Column("image", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("offers", "image")
    op.drop_constraint(None, "offer_types", type_="foreignkey")
    op.drop_column("offer_types", "offer_id")
    op.drop_table("offer_price_detailss")
    # ### end Alembic commands ###
